/* ==========================================================
   Local Connect — data.js
   Firebase config + seed listings.
   
   HOW TO SET UP FIREBASE (free):
   1. Go to https://console.firebase.google.com
   2. Create a new project (e.g. "local-connect")
   3. Click "Web" to add a web app
   4. Copy your firebaseConfig values below
   5. In Firebase console → Build → Realtime Database → Create database
      → Start in TEST MODE (rules allow read/write for 30 days)
   6. In Firebase console → Build → Authentication → Sign-in method
      → Enable "Email/Password"
   7. Open your app — everything is now realtime!
   ========================================================== */

// ── Replace these with YOUR Firebase project values ──────────
const FIREBASE_CONFIG = {
  apiKey: "AIzaSyBKe5bVnXU1_kB-GWDrsoX0j3J_GK9nWuw",
  authDomain: "localconnect-335cd.firebaseapp.com",
  databaseURL: "https://localconnect-335cd-default-rtdb.firebaseio.com",
  projectId: "localconnect-335cd",
  storageBucket: "localconnect-335cd.firebasestorage.app",
  messagingSenderId: "605777167680",
  appId: "1:605777167680:web:53ad7557aff272cfa6a6a5"
};
// ─────────────────────────────────────────────────────────────

/* Seed listings injected once when DB is empty */
const SEED_LISTINGS = [
  {
    title: 'Handmade Tote Bag',
    description: 'Woven by hand using abaca fibers. Strong, eco-friendly, and perfect for the palengke or a beach trip. Available in natural and brown.',
    price: 280,
    stockQuantity: 1,
    location: 'Barangay San Antonio',
    category: 'Crafts',
    sellerName: 'Maria Santos',
    sellerEmail: 'maria@demo.com',
    allowReservations: true,
    meetUpAvailable: true,
    deliveryAvailable: true,
    postedAt: Date.now() - 7200000,
    rating: 4.9,
    reviews: 18,
  },
  {
    title: 'Homemade Ube Halaya',
    description: 'Freshly made ube halaya in 250g jars. Made with real ube from the farm, coconut milk, and condensed milk. No preservatives.',
    price: 120,
    stockQuantity: 1,
    location: 'Barangay Maligaya',
    category: 'Food',
    sellerName: 'Lola Coring',
    sellerEmail: 'coring@demo.com',
    allowReservations: true,
    meetUpAvailable: true,
    deliveryAvailable: true,
    postedAt: Date.now() - 10800000,
    rating: 5.0,
    reviews: 42,
  },
  {
    title: 'Used iPhone 11 (64GB)',
    description: 'iPhone 11 in good condition. Battery at 87%. Minor scratches on the back. Screen is perfect. Comes with original charger.',
    price: 14500,
    stockQuantity: 1,
    location: 'Barangay Poblacion',
    category: 'Devices',
    sellerName: 'Kuya Ben',
    sellerEmail: 'ben@demo.com',
    allowReservations: true,
    meetUpAvailable: true,
    deliveryAvailable: true,
    postedAt: Date.now() - 18000000,
    rating: 4.7,
    reviews: 9,
  },
  {
    title: 'Ukay-ukay Bundle (5 pcs)',
    description: 'Preloved clothes from Korea and Japan. All in good condition, no holes or stains. Sizes S-L mixed. Pants, tops, and a jacket included.',
    price: 350,
    stockQuantity: 5,
    location: 'Barangay Bagong Silang',
    category: 'Clothes',
    sellerName: 'Ate Rach',
    sellerEmail: 'rach@demo.com',
    allowReservations: false,
    meetUpAvailable: true,
    deliveryAvailable: false,
    postedAt: Date.now() - 86400000,
    rating: 4.8,
    reviews: 27,
  },
  {
    title: 'Laptop Fan Cleaning Service',
    description: 'Nagbibigay ng serbisyo ng paglilinis ng laptop. Kasama na ang thermal paste replacement at dust blowout. Lahat ng brand.',
    price: 250,
    stockQuantity: 1,
    location: 'Barangay Silangan',
    category: 'Services',
    sellerName: 'Mang Danny Techs',
    sellerEmail: 'danny@demo.com',
    allowReservations: true,
    meetUpAvailable: true,
    deliveryAvailable: true,
    postedAt: Date.now() - 172800000,
    rating: 4.6,
    reviews: 33,
  },
  {
    title: 'Resin-coated Dried Flowers',
    description: 'Handcrafted resin bookmarks and keychains made with dried flowers from my garden. Each piece is unique. Great for gifts!',
    price: 95,
    stockQuantity: 1,
    location: 'Barangay San Jose',
    category: 'Crafts',
    sellerName: 'Bea Creates',
    sellerEmail: 'bea@demo.com',
    allowReservations: true,
    meetUpAvailable: true,
    deliveryAvailable: true,
    postedAt: Date.now() - 259200000,
    rating: 5.0,
    reviews: 56,
  },
  {
    title: 'Brand New HDMI Cable 2m',
    description: 'Never opened. Bought extra. Supports 4K 60fps. Compatible with TV, monitors, laptops, and consoles.',
    price: 180,
    stockQuantity: 1,
    location: 'Barangay Pinyahan',
    category: 'Devices',
    sellerName: 'TechDrop PH',
    sellerEmail: 'techdrop@demo.com',
    allowReservations: false,
    meetUpAvailable: true,
    deliveryAvailable: false,
    postedAt: Date.now() - 345600000,
    rating: 4.5,
    reviews: 7,
  },
  {
    title: 'Puto Bumbong (dozen)',
    description: 'Classic puto bumbong sold by the dozen. Topped with grated coconut and muscovado. Available Fridays to Sundays only.',
    price: 90,
    stockQuantity: 12,
    location: 'Barangay Dela Paz',
    category: 'Food',
    sellerName: 'Nanay Flor',
    sellerEmail: 'flor@demo.com',
    allowReservations: true,
    meetUpAvailable: true,
    deliveryAvailable: true,
    postedAt: Date.now() - 432000000,
    rating: 4.9,
    reviews: 61,
  },
  {
    title: 'Second-hand School Bag',
    description: 'Gently used JanSport backpack. Still very sturdy. Navy blue color. Fits 15-inch laptop. Great for students.',
    price: 400,
    stockQuantity: 1,
    location: 'Barangay Pitogo',
    category: 'Pre-loved',
    sellerName: 'Carlos R.',
    sellerEmail: 'carlos@demo.com',
    allowReservations: false,
    meetUpAvailable: true,
    deliveryAvailable: false,
    postedAt: Date.now() - 518400000,
    rating: 4.3,
    reviews: 4,
  },
  {
    title: 'Freelance Graphic Design',
    description: 'Logo, social media post, tarpaulin, flyers — lahat kaya ko. Turnaround: 1-3 days. May mga samples sa DM.',
    price: 500,
    stockQuantity: 1,
    location: 'Barangay Commonwealth',
    category: 'Services',
    sellerName: 'PixelAte Studio',
    sellerEmail: 'pixelate@demo.com',
    allowReservations: true,
    meetUpAvailable: true,
    deliveryAvailable: true,
    postedAt: Date.now() - 604800000,
    rating: 4.8,
    reviews: 89,
  },
];